# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: kindlab.fhir.vbai
canonical: https://voicecollab.ai/fhir
name: VoiceaBiomarkerforAI
description: Implementation Guide for Voice Biomarker for AI FHIR Profiles
status: draft # draft | active | retired | unknown
version: 1.0.0 #0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2022+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: KinD Lab
  url: http://fhir.kindlab.sickkids.ca

#
dependencies:
  hl7.fhir.us.core: 5.0.1
  hl7.fhir.uv.extensions: 1.0.0
  hl7.terminology: 5.2.0
  # hl7.fhir.ca-baseline:
  #   id: baseline
  #   uri: https://build.fhir.org/ig/HL7-Canada/ca-baseline/
  #   version: 1.1.0
#   hl7.fhir.us.mcode:
#     id: mcode
#     uri: http://hl7.org/fhir/us/mcode/ImplementationGuide/hl7.fhir.us.mcode
#     version: 1.0.0
#

#
#
# The parameters property represents IG.definition.parameter. Rather
# than a list of code/value pairs (as in the ImplementationGuide
# resource), the code is the YAML key. If a parameter allows repeating
# values, the value in the YAML should be a sequence/array. For a
# partial list of allowed parameters see:
# https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
#
# parameters:
#   excludettl: true
#   validation: [allow-any-extensions, no-broken-links]
#
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │ The menu property will be used to generate the input/menu.xml file. The menu is represented    │
# │ as a simple structure where the YAML key is the menu item name and the value is the URL.       │
# │ The IG publisher currently only supports one level deep on sub-menus. To provide a             │
# │ custom menu.xml file, do not include this property and include a `menu.xml` file in            │
# │ input/includes. To use a provided input/includes/menu.xml file, delete the "menu"              │
# │ property below.                                                                                │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Guidance: guidance.html
  Artifacts: artifacts.html
  Change Log: changelog.html
  Tutorial: tutorial_table_of_contents.html
  
pages:
   index.md:
   guidance.md:
   artifacts.html:
   changelog.md:
   tutorial_mood.md:
   tutorial_voice.md:
   tutorial_peds.md:
   tutorial_respiratory.md:
   tutorial_neuro.md:
   tutorial_table_of_contents.md:
   brief_fhir_intro.md:
