name: Build the IG
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
    # Install ruby
    # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

    # Install Jekyll
    # https://jekyllrb.com/docs/installation/ubuntu/
      - name: "Install Jekyll"
        shell: bash
        run: |
          gem install jekyll bundler
          jekyll -v

    # Install node if SUSHI is needed
    # https://github.com/actions/setup-node
      - name: "Install Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "18"

    # Install SUSHI if needed
      - name: "Install SUSHI"
        shell: bash
        run: |
          npm install -g fsh-sushi@2.7.0
          sushi --version
          sushi .


    # Install GOFSH if needed
      - name: "Install GOFSH"
        shell: bash
        run: |
          npm install -g gofsh@1.6.4
          gofsh --version

    # Install reproschema2fhir if needed
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: kind-lab/reproschema-to-fhir  
          path: './tofsh'
    
    # Call Gofsh if needed
      - name: Checkout
        shell: bash
        run: |
          cd ./tofsh
          pip install -e .
          ls
          cp .env.example .env
          echo ""
          cd b2ai-reproschemav3.1
          ls -a
          cd ..
          echo -e "CODESYSTEM_URI = https://voicecollab.ai/fhir/CodeSystem/\nVALUESET_URI = https://voicecollab.ai/fhir/ValueSet/\nQUESTIONNAIRE_URI = https://voicecollab.ai/fhir/Questionnaire/\nQUESTIONNAIRE_LANGUAGE = en\nFHIR_QUESTIONNAIRE_MODE = AnswerOptions" >> .env
          
          
    # ./job.sh
          # ls
          # cd ..
          # cp -r ./tofsh/output/ .
          # gofsh /
          # cd output
          # ls -a

    #   - name: "Download the IG Publisher"
    #     shell: bash
    #     run: |
    #       mkdir ./input-cache
    #       curl -sS -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./input-cache/publisher.jar
    #       chmod +x ./input-cache/publisher.jar
    # # Download the IG Publisher
    #   - name: "Create IG"
    #     shell: bash
    #     run: |
    #       java -jar -Xms4096M -Xmx6144M -XX:NewRatio=1 -XX:-UseAdaptiveSizePolicy input-cache/publisher.jar ig.ini
    #       mkdir -p ./git-output/vbai-fhir
    #       cp -r ./output/* ./git-output/vbai-fhir 
    #       echo "Kind Lab GitHub Pages for external webpages." > ./git-output/README.md
      

      
    #   # Deploy IG
    #   - name: Deploy to external repository
    #     uses: cpina/github-action-push-to-another-repository@main
    #     env: 
    #       SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
    #     with:
    #       source-directory: 'git-output'
    #       destination-github-username: 'kind-lab'
    #       destination-repository-name: 'kind-lab.github.io'
       
          
     